brainstorm/brainstorm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('storm.urls')),
    path('api/v1/', include('social_django.urls', namespace='social')),
]

brainstorm/storm/urls.py
from django.urls import path
from . import views

app_name = 'storm'

urlpatterns = [
    path('', views.login, name='login'),
    path('home/', views.home, name='home'),
    path('idea/<int:id>/', views.idea, name='idea'),
    path('logout/', views.logout_user, name='logout_user'),
    path('idea/form/', views.idea_form, name='idea_form'),
    path('idea/submit/', views.idea_submit, name='idea_submit'),
    path('selection/<int:id>/', views.selection, name="selection"),
    path('comment/<int:id>/', views.comment, name="comment"),
    path('status/<int:id>/', views.status, name="status"),
    path('jury/', views.jury, name='jury'),
    path('filterdate/', views.filterdate, name='filterdate'),
]

brainstorm/storm/models.py
from django.db import models

# Improvement Areas List for Idea
class Improvement_Area(models.Model):
    area_title = models.CharField(max_length=200, null=False, blank=False)

    def __str__(self):
        return self.area_title 

# Impact 
class Impact(models.Model):
    impact = models.CharField(max_length=200, null=False, blank=False)

    def __str__(self):
        return self.impact

# Judge Addition
class Judge(models.Model):
    judge_name = models.CharField(max_length=200, null=False, blank=False)
    judge_mail = models.EmailField(default=None, null=False, blank=False)

    def __str__(self):
        return self.judge_name

# Idea Submission
class Idea(models.Model):
    # Autofill Details
    idea_creator_name = models.CharField(max_length=200, null=True, blank=True)
    idea_creator_mail = models.EmailField(default=None, null=False, blank=False)
    idea_creation_date = models.DateTimeField(auto_now_add=True)

    # User Filled Details
    idea_close_date = models.DateTimeField(default=None, null=True, blank=True)
    idea_improvement = models.CharField(default=None, max_length=200, null=False, blank=False)
    idea_title = models.CharField(default=None, max_length=200, null=False, blank=False)
    idea_description = models.TextField(default=None, null=True, blank=True)
    idea_impact = models.CharField(default=None, max_length=200, null=False, blank=False)
    idea_file_1 = models.FileField(upload_to='', null=True, blank=True)
    idea_file_2 = models.FileField(upload_to='', null=True, blank=True)
    idea_file_3 = models.FileField(upload_to='', null=True, blank=True)
    idea_file_4 = models.FileField(upload_to='', null=True, blank=True)
    idea_file_5 = models.FileField(upload_to='', null=True, blank=True)

    # Judge Status
    idea_status = models.CharField(max_length=200, default=None, null=True, blank=True, choices=[('WIP', 'WIP'), ('Implemented', 'Implemented'), ('Hold', 'Hold'), ('Cancel', 'Cancel'), ('Close', 'Close')])

    def __str__(self):
        return self.idea_creation_date

# QC Status for Idea
class Idea_QC(models.Model):
    # Same id as of idea
    idea_id = models.IntegerField(default=0, null=False, blank=False)
    
    # Autofill Details
    idea_qc_name = models.CharField(max_length=200, null=True, blank=True)
    idea_qc_mail = models.EmailField(default=None, null=False, blank=False)
    idea_qc_date = models.DateTimeField(auto_now_add=True)
    idea_join = models.ForeignKey(Idea, on_delete=models.CASCADE)

    # QC Details
    idea_qc_remark = models.TextField(default=None, null=True, blank=True)
    idea_qc_status = models.CharField(max_length=200, default='Pending', choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')])

    def __str__(self):
        qc_data = str(self.idea_id) + ', ' + self.idea_qc_name + ', ' + self.idea_qc_status
        return qc_data

# Comment Section
class Comment(models.Model):
    # Same id as of idea
    comment_id = models.IntegerField(default=0, null=False, blank=False)

    # Autofill Details
    commenter_name = models.CharField(max_length=200, null=True, blank=True)
    commenter_mail = models.EmailField(default=None, null=False, blank=False)
    comment_date = models.DateTimeField(auto_now_add=True)
    comment_join = models.ForeignKey(Idea, on_delete=models.CASCADE)

    # Comment
    comment = models.TextField(default=None, null=False, blank=False)

    def __str__(self):
        comment_data = str(self.comment_id) + ', ' + self.commenter_name
        return comment_data

brainstorm/storm/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.conf import settings
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth import login, logout
from django.views.decorators.csrf import csrf_exempt
from .models import Idea, Judge, Impact, Improvement_Area, Idea_QC, Comment
from datetime import datetime
import pandas as pd
from sqlalchemy import create_engine

def authentication_check(user):
    return user.is_authenticated

def login(request):
    if request.user.is_authenticated:
        return redirect('storm:home')
    return render(request, 'storm/login.html')

@user_passes_test(authentication_check, login_url='/', redirect_field_name=None)
def logout_user(request):
    logout(request)
    return redirect('storm:login')

@user_passes_test(authentication_check, login_url='/', redirect_field_name=None)
def home(request):
    try:
        engine = create_engine('postgresql://analytics:analytics@123@ec2-34-246-108-106.eu-west-1.compute.amazonaws.com:5432/iadatabase')
        df_aws = pd.read_sql_query('select * from "headcount_master"', con=engine)
        df = df_aws[['Email Id', 'Sub-Department', 'DF Site', '1st Level Reporting', '2nd Level Reporting']]
        df.columns = ['email', 'dept', 'location', 'first_level', 'second_level']
    except:
        data = [['anubhav.kumar27@gmail.com', 'Analytics', 'Noida', 'Sanjeev Rathore', 'Sanjeev Agarwal']]
        df = pd.DataFrame(data, columns = ['email', 'dept', 'location', 'first_level', 'second_level']) 
    user_name = request.user.first_name
    user_email = request.user.email
    ideas = Idea.objects.all().order_by('-id')
    new_ideas = [i.idea_id for i in Idea_QC.objects.all()]
    selected_ideas = [i.idea_id for i in Idea_QC.objects.filter(idea_qc_status='Accepted')]
    your_idea = Idea.objects.filter(idea_creator_mail=user_email)
    judges = [i.judge_mail for i in Judge.objects.all()]
    return render(request, 'storm/home.html', {"user_email":user_email, "user_name":user_name, "ideas":ideas, "judges":judges, "new_ideas":new_ideas, "selected_ideas":selected_ideas, "your_idea":your_idea, "df":df})

@user_passes_test(authentication_check, login_url='/', redirect_field_name=None)
def idea(request, id):
    try:
        engine = create_engine('postgresql://analytics:analytics@123@ec2-34-246-108-106.eu-west-1.compute.amazonaws.com:5432/iadatabase')
        df_aws = pd.read_sql_query('select * from "headcount_master"', con=engine)
        df = df_aws[['Email Id', 'Sub-Department', 'DF Site', '1st Level Reporting', '2nd Level Reporting']]
        df.columns = ['email', 'dept', 'location', 'first_level', 'second_level']
    except:
        data = [['anubhav.kumar27@gmail.com', 'Analytics', 'Noida', 'Sanjeev Rathore', 'Sanjeev Agarwal']]
        df = pd.DataFrame(data, columns = ['email', 'dept', 'location', 'first_level', 'second_level']) 
    user_name = request.user.first_name
    user_email = request.user.email
    ideas = Idea.objects.filter(pk = id)
    idea_qc_id = [i.idea_id for i in Idea_QC.objects.all()]
    idea_qc = [i for i in Idea_QC.objects.filter(idea_id=id)]
    comments = Comment.objects.filter(comment_id=id).order_by('-id')
    judges = [i.judge_mail for i in Judge.objects.all()]
    return render(request, 'storm/idea.html', {"user_email":user_email, "user_name":user_name, "ideas":ideas, "judges":judges, "idea_qc_id":idea_qc_id, "idea_qc":idea_qc, "comments":comments, "df":df})

@user_passes_test(authentication_check, login_url='/', redirect_field_name=None)
def idea_form(request):
    user_name = request.user.first_name
    user_email = request.user.email
    creator_name = request.user.first_name
    creator_email = request.user.email
    impact = Impact.objects.all().order_by('id')
    improvement = Improvement_Area.objects.all().order_by('id')
    judges = [i.judge_mail for i in Judge.objects.all()]
    return render(request, 'storm/form.html', {"user_email":user_email, "user_name":user_name, "creator_email":creator_email, "creator_name":creator_name, "impact":impact, "improvement":improvement, "judges":judges})

@user_passes_test(authentication_check, login_url='/', redirect_field_name=None)
@csrf_exempt
def idea_submit(request):
    if request.method =="POST":
        # Creator Details
        idea_creator_name = request.user.first_name
        idea_creator_mail = request.user.email

        # Idea Details
        idea_improvement = request.POST.get("idea_improvement")
        idea_title = request.POST.get("idea_title")
        idea_description = request.POST.get("idea_description")
        idea_impact = request.POST.get("idea_impact")
        idea_file_1 = request.FILES.get('idea_file_1')
        idea_file_2 = request.FILES.get('idea_file_2')
        idea_file_3 = request.FILES.get('idea_file_3')
        idea_file_4 = request.FILES.get('idea_file_4')
        idea_file_5 = request.FILES.get('idea_file_5')

        # Save Idea
        obj = Idea.objects.create(idea_creator_name=idea_creator_name,
                            idea_creator_mail=idea_creator_mail,
                            idea_improvement=idea_improvement,
                            idea_title=idea_title, 
                            idea_description=idea_description, 
                            idea_impact=idea_impact, 
                            idea_file_1=idea_file_1,
                            idea_file_2=idea_file_2,
                            idea_file_3=idea_file_3,
                            idea_file_4=idea_file_4,
                            idea_file_5=idea_file_5,
                            )
        # send_mail(f'Your ID is {obj.id}',
        #           'Hi,\n\nYour Idea is received.', settings.EMAIL_HOST_USER,[request.user.email])
                        
        return redirect('storm:home')
    return redirect('storm:home')

# Accept or Reject IDEA_QC
@user_passes_test(authentication_check, login_url='/', redirect_field_name=None)
def selection(request, id):
    if request.method =="POST":
        # Creator Detail
        idea_qc_name = request.user.first_name
        idea_qc_mail = request.user.email

        # Accept/Reject
        idea_id = id
        idea_join = Idea.objects.get(pk=id)
        idea_qc_remark = request.POST.get("idea_qc_remark")
        idea_qc_status = request.POST.get("idea_qc_status")

        # Create QC status
        Idea_QC.objects.create(idea_id=idea_id,
                            idea_qc_name=idea_qc_name,
                            idea_qc_mail=idea_qc_mail,
                            idea_join=idea_join,
                            idea_qc_remark=idea_qc_remark,
                            idea_qc_status=idea_qc_status
                            )
        # send_mail(f'Your Idea is {idea_qc_status}',f'Hi,\n\nremarks on your idea is {idea_qc_remark}.', settings.EMAIL_HOST_USER, [idea_qc_mail])
        
        return redirect('storm:idea', id=id)
    return redirect('storm:home')

# Comment Data
@user_passes_test(authentication_check, login_url='/', redirect_field_name=None)
def comment(request, id):
    if request.method == 'POST':
        # Creator Detail
        commenter_name = request.user.first_name
        commenter_mail = request.user.email

        # Get Comment
        comment_id = id
        comment = request.POST.get("comment")
        comment_join = Idea.objects.get(pk=id)

        # Create comment object
        Comment.objects.create(comment_id=comment_id,
                            commenter_name=commenter_name,
                            commenter_mail=commenter_mail,
                            comment_join=comment_join,
                            comment=comment
                            )
        
        return HttpResponse('')
    return redirect('storm:idea', id=id)

# Update Idea Status
@user_passes_test(authentication_check, login_url='/', redirect_field_name=None)
def status(request, id):
    if request.method == 'POST':
        idea_close_date = datetime.now()
        idea_status = request.POST.get('idea_status')

        # Update
        Idea.objects.filter(pk=id).update(idea_close_date=idea_close_date, idea_status=idea_status)
        return HttpResponse('')
    return redirect('storm:idea', id=id)

# All Ideas
@user_passes_test(authentication_check, login_url='/', redirect_field_name=None)
def jury(request):
    try:
        engine = create_engine('postgresql://analytics:analytics@123@ec2-34-246-108-106.eu-west-1.compute.amazonaws.com:5432/iadatabase')
        df_aws = pd.read_sql_query('select * from "headcount_master"', con=engine)
        df = df_aws[['Email Id', 'Sub-Department', 'DF Site', '1st Level Reporting', '2nd Level Reporting']]
        df.columns = ['email', 'dept', 'location', 'first_level', 'second_level']
    except:
        data = [['anubhav.kumar27@gmail.com', 'Analytics', 'Noida', 'Sanjeev Rathore', 'Sanjeev Agarwal']]
        df = pd.DataFrame(data, columns = ['email', 'dept', 'location', 'first_level', 'second_level']) 
    user_name = request.user.first_name
    user_email = request.user.email
    ideas = Idea.objects.all()
    judges = [i.judge_mail for i in Judge.objects.all()]
    all_ideas = Idea_QC.objects.all()
    return render(request, 'storm/jury.html', {"user_email":user_email, "user_name":user_name, "ideas":ideas, "judges":judges, "all_ideas":all_ideas, "df":df})


@user_passes_test(authentication_check, login_url='/', redirect_field_name=None)
@csrf_exempt
def filterdate(request):
    if request.method == 'POST':
        try:
            engine = create_engine('postgresql://analytics:analytics@123@ec2-34-246-108-106.eu-west-1.compute.amazonaws.com:5432/iadatabase')
            df_aws = pd.read_sql_query('select * from "headcount_master"', con=engine)
            df = df_aws[['Email Id', 'Sub-Department', 'DF Site', '1st Level Reporting', '2nd Level Reporting']]

brainstorm/storm/templates/storm/empty.html
{% load staticfiles %}
<div class="flex flex-col-reverse md:flex-row items-center empty">
    <div class="flex-1 overflow-hidden h-full">
        <img src="{% static 'storm/images/empty.svg' %}" alt="" class="w-full h-full">
    </div>
    <div class="flex-1">
        <h2 class="text-2xl font-bold md:text-3xl">Sorry the box is empty</h2>
        <p>Please put your idea inside the box and make us happy</p>
        <a href="{% url 'storm:idea_form' %}" class="px-6 py-2 text-center md:w-64 login-button">Get started</a>
    </div>
</div>

brainstorm/storm/templates/storm/home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block Title %}Home | {% endblock %}

{% block body %}

<div class="">
    <div class="w-full h-32 flex items-center justify-center">
        <h1 class="text-3xl font-bold">Welcome {{ user_name }}!</h1>
    </div>

    {% if ideas %}
    <div class="idea_box">
        {% if user_email in judges %}
            <div class="sticky top-0 bg-black flex flex-col items-center md:flex-row">
                <!-- <div class="flex-1">
                    <input type="text" class="search rounded py-2 px-4" placeholder="search ideas...">
                </div> -->
                <ul class="tab flex-1 flex flex-col z-10 mb-2 md:flex-row md:justify-end">
                    <li class="p-4 mr-2 font-bold lowercase cursor-pointer md:tab-active" data-class="new_ideas">New Ideas</li>
                    <li class="p-4 font-bold lowercase cursor-pointer" data-class="selected_ideas">Selected Ideas</li>
                </ul>
            </div>
            {% include 'storm/new_idea.html' %}
            {% include 'storm/selected_idea.html' %}
        {% else %}
            {% include 'storm/your_idea.html' %}
        {% endif %}
    </div>
    {% else %}
        {% include 'storm/empty.html' %}
    {% endif %}
</div>

{% endblock %}

{% block scripts %}
<script src="{% static 'storm/js/main.js' %}"></script>
{% endblock %}

brainstorm/storm/templates/storm/idea.html
{% extends 'base.html' %}

{% block Title %}Idea | {% endblock %}

{% block body %}

{% for i in ideas %}

<div class="md:w-3/4 md:m-auto">
    <section class="mb-4 flex items-center">
        <h1 class="flex-1 text-2xl font-bold md:text-3xl">{{i.idea_title}}</h1>
        <a href="{% url 'storm:home' %}" class="bg-blue-300 text-blue-800 p-2 rounded cursor-pointer hidden md:block"><i class="fas fa-chevron-left mr-2"></i> Back to home</a>
    </section>

    <span class="idea_id hidden">{{i.id}}</span>

    {% for j in idea_qc %}
    {% if j.idea_qc_status == 'Accepted' %}
    <div class="mb-8">
        <label for="" class="block text-gray-600 mb-1">Idea Status</label>
        {% if user_email in judges %}
        {% if i.idea_status == 'Cancel' %}
        <span class="bg-red-900 px-2 py-1 rounded">{{ i.idea_status }}</span>
        {% elif i.idea_status == 'Close' %}
        <span class="bg-blue-900 px-2 py-1 rounded">{{ i.idea_status }}</span>
        {% else %}
        <form action="" class="status_form relative">{% csrf_token %}
            <select name="idea_status" class="py-2 px-3 form__select w-1/4 rounded status border cursor-pointer">
                <option value="">--Status--</option>
                <option value="WIP">WIP</option>
                <option value="Implemented">Implemented</option>
                <option value="Hold">Hold</option>
                <option value="Close">Close</option>
                <option value="Cancel">Cancel</option>
            </select>
        </form>
        <section class="absolute top-0 bottom-0 left-0 right-0 z-20 dialog flex items-center justify-center hidden">
            <div class="bg-gray-900 px-6 py-3 md:px-8 md:py-4 rounded">
                <p class="mb-2 dialog__p">Do you really want to close this idea?</p>
                <button type="button" id="idea_status_yes" class="bg-blue-600 px-4 py-1 rounded mr-2">Yes</button>
                <button type="button" id="idea_status_no" class="border border-gray-100 rounded px-4 py-1">No</button>
            </div>
        </section>
        {% endif %}
        {% else %}
        <span class="bg-blue-900 px-2 py-1 rounded">{{ i.idea_status }}</span>
        {% endif %}
    </div>
    {% endif %}
    {% endfor %}

    <section class="mb-8">
        <p class="font-semibold flex flex-col md:flex-row text-purple-600">
            <span class="flex flex-col md:flex-1 text-sm">
                <span class="mb-2"><i class="far fa-user mr-2"></i>{{ i.idea_creator_name }}</span>
                <span class="mb-2"><i class="far fa-envelope mr-2"></i>{{ i.idea_creator_mail }}</span>
                <span class=""><i class="far fa-clock mr-2"></i>{{i.idea_creation_date|date}}</span>
            </span>
            <span class="flex flex-col md:flex-1 text-sm">
            <span class="mb-2"><i class="fas fa-users mr-2"></i>
                {% for j in df.itertuples %} 
                {% if i.idea_creator_mail == j.email  %}
                    {{ j.dept }}
                {% endif %} 
                {% endfor %} 
            </span>
            <span class="mb-2"><i class="fas fa-map-marker-alt mr-2"></i>
                {% for j in df.itertuples %} 
                {% if i.idea_creator_mail == j.email  %}
                    {{ j.location }}
                {% endif %} 
                {% endfor %} 
            </span>
            <span class=""><i class="fas fa-user-tie mr-2"></i>
                {% for j in df.itertuples %} 
                {% if i.idea_creator_mail == j.email  %}
                    {{ j.first_level }}
                {% endif %} 
                {% endfor %} 
            </span>
            </span>
        </p>
    </section>

    <section class="flex flex-col md:flex-row mb-8">
        <p class="flex-1">
            <span class="block text-md text-gray-500">Improvement Area</span>
            <span class="block text-lg">{{ i.idea_improvement }}</span>
        </p>

        <p class="flex-1">
            <span class="block text-md text-gray-500">Impact</span>
            <span class="block text-lg">{{ i.idea_impact }}</span>
        </p>
    </section>

    {% if i.idea_file_1 %}
    <section class="mb-8 md:w-2/3">
        <div class="md:flex-1 border-t border-b border-gray-900 py-2">
            <p class="text-md text-gray-500 flex cursor-pointer document-caret">
                <span class="flex-1">Attached Document(s):</span>
                <span class="bg-gray-900 px-2 rounded"><i class="fas fa-caret-down"></i></span>
            </p>
            <ul class="text-lg bg-gray-900 px-6 py-2 mt-2 divide-y divide-gray-700 rounded drop-caret hidden">
                <li class="mb-1"><a href="/static{{i.idea_file_1.url}}" class="text-indigo-300">{{ i.idea_file_1 }}</a></li>
                {% if i.idea_file_2 %}
                <li class="mb-1"><a href="/static{{i.idea_file_2.url}}" class="text-indigo-300">{{ i.idea_file_2 }}</a></li>
                {% if i.idea_file_3 %}
                <li class="mb-1"><a href="/static{{i.idea_file_3.url}}" class="text-indigo-300">{{ i.idea_file_3 }}</a></li>
                {% if i.idea_file_4 %}
                <li class="mb-1"><a href="/static{{i.idea_file_4.url}}" class="text-indigo-300">{{ i.idea_file_4 }}</a></li>
                {% if i.idea_file_5 %}
                <li class=""><a href="/static{{i.idea_file_5.url}}" class="text-indigo-300">{{ i.idea_file_5 }}</a></li>
                {% endif %}
                {% endif %}
                {% endif %}
                {% endif %}
            </ul>
        </div>
    </section>
    {% endif %}

    <article class="mb-8">
        <p class="text-md text-gray-500 mb-2">Description</p>
        <p class="text-lg">{{ i.idea_description }}</p>
    </article>

    {% if idea_qc %}
    <article class="mb-8">
        {% for qc in idea_qc %}
        <p class="text-md text-gray-500 mb-2">
            {% if qc.idea_qc_status == 'Accepted' %}Accept 
            {% elif qc.idea_qc_status == 'Rejected' %}Reject 
            {% endif %}
            Remark
        </p>
        <p class="text-lg remark-tab">{{ qc.idea_qc_remark }}</p>
        {% endfor %}
    </article>
    {% endif %}

    {% if i.id not in idea_qc_id %}
    {% if user_email in judges %}
    <!-- Accept/Reject Form -->
    <section class="judge-action">
        <a class="button__accept cursor-pointer bg-purple-700 py-2 px-8 mr-3">Accept</a>
        <a class="button__reject cursor-pointer border border-red-500 text-red-500 py-2 px-8">Reject</a>
    </section>
    <form action="{% url 'storm:selection' id=i.id %}" method="POST" class="judge-form hidden" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form__fieldset">
            <div class="mb-6">
                <label class="block text-gray-500 text-sm font-bold mb-2 remark-label">Reason for acceptance</label>
                <div class="form__input-div">
                    <textarea name="idea_qc_remark" class="appearance-none py-2 px-3 form__input form__textarea"  placeholder="So the reason is..." required></textarea>
                    <span class="form__input-focus" style="bottom: 7px;"></span>
                </div>
            </div>

            <select name="idea_qc_status" class="hidden">
                <option value="Accepted">Accepted</option>
                <option value="Rejected">Rejected</option>
            </select>
            <button class="py-2 px-6 button-submit sm:block">Get Set Go</button>
        </fieldset>
    </form>
    {% endif %}
    {% endif %}

    {% for j in idea_qc %}
    {% if j.idea_qc_status == 'Accepted' %}
    <!-- Comment Box -->
    <h1 class="text-gray-500 mb-4">Comment Section</h1>

    <section class="mt-4 border border-gray-800 p-4 md:w-2/3">

        <form action="" method="POST" class="comment-form mb-2">{% csrf_token %}
            <fieldset class="form__fieldset">
                <!-- <label class="block text-gray-500 text-sm font-bold mb-2">Comment</label> -->
                <div class="flex">
                    <div class="form__input-div">
                        <textarea name="comment" class="appearance-none py-2 px-3 form__input form__textarea comment_box"  placeholder="Your Comment..." required></textarea>
                        <span class="form__input-focus" style="bottom: 7px;"></span>
                    </div>
                    <button class="send-button bg-purple-700 text-gray-200 px-4"><i class="fas fa-arrow-right"></i></button>
                </div>
            </fieldset>
        </form>

        <section class="comment-list">
            {% for k in comments %}
            {% if k.commenter_mail != user_email %}
            <div class="border-l-4 px-4 py-2 bg-gray-900 mb-2">
                <p class="text-sm flex">
                    <span class="text-green-500 flex-1">{{k.commenter_name}}</span>
                    <span class="text-gray-600">{{k.comment_date|date}}</span>
                </p>
                <p>{{k.comment}}</p>
            </div>
            {% else %}
            <div class="border-r-4 px-4 py-2 bg-teal-900 mb-2">
                <p class="text-sm flex flex-row-reverse">
                    <span class="text-gray-400">{{k.commenter_name}}</span>
                    <span class="text-gray-500 flex-1">{{k.comment_date}}</span>
                </p>
                <p class="text-right">{{k.comment}}</p>
            </div>
            {% endif %}
            {% endfor %}
        </section>
    </section>
    {% endif %}
    {% endfor %}

</div>

{% endfor %}

{% endblock %}

{% block scripts %}
{% load staticfiles %}
<script>
    const userName = `{{user_name}}`;

    {% for i in ideas %}
    {% if i.idea_status != None %}
    const statusValue = `{{i.idea_status}}`;
    {% else %}
    const statusValue = '';
    {% endif %}
    {% endfor %}
</script>
<script src="{% static 'storm/js/idea.js' %}"></script>
{% endblock %}

brainstorm/storm/templates/storm/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    {% load staticfiles %}
    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'storm/images/favicon.svg' %}" type="image/x-icon">
    
    <!-- Tailwind CSS -->
    <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
    
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'storm/css/main.css' %}">
    
    <title>Brainstorm</title>
</head>
<body>
    <div class="block md:flex lg:flex h-screen login-div">
        <div class="relative flex flex-col justify-center md:pl-20 md:flex-1 lg:flex-1">
            <h1 class="font-bold text-2xl text-blue-400 uppercase md:text-5xl lg:text-6xl login-heading">
                <span>Brainstorm</span>
            </h1>
            <span class="text-base login-tag mb-4">Share your idea to improve the workflow of company and win exciting prices.</span>
            <a href="{% url 'social:begin' 'google-oauth2' %}" class="px-6 py-2 text-center md:w-48 login-button">Login</a>
        </div>
        <div class="relative md:flex-1 lg:flex-1">
            <img src="{% static 'storm/images/idea.svg' %}" alt="idea" srcset="{% static 'storm/images/idea.svg' %}" class="h-full z-10 login-image">
            <div id="particles-js" class="absolute top-0 left-0 w-full h-full"></div>
        </div>
    </div>

    <!-- Scripts -->
    <script src="https://cdn.jsdelivr.net/npm/particles.js@2.0.0/particles.min.js"></script>
    <script src="{% static 'storm/js/particles.js' %}"></script>
</body>
</html>